### PR TITLE
PicknikTwistControler -> PicknikTwistController

### PR DESCRIPTION
**Pull request by abake48**
Correct the name of the twist controller

### CODE REVIEW

**Review by MarqRazz — APPROVED** [review]
Good catch!

**Review by cmelliott2 — APPROVED** [review]

**Review by moriarty — APPROVED** [review]

**Comment by moriarty** [comment]
Yep good catch. And obviously this is ABI breaking because the original name was a typo :man_facepalming: sorry

**Comment by moriarty** [comment]
This typo got released into Humble, but Iron and Rolling were being held for sync.

Rolling: https://github.com/ros/rosdistro/pull/37912
Iron: https://github.com/ros/rosdistro/pull/37914

**Comment by moriarty** [comment]
https://github.com/ros/rosdistro/pull/37980
https://github.com/ros/rosdistro/pull/37981
https://github.com/ros/rosdistro/pull/37982

**Pull request merged**
